<?php
/**
 * @var \Tournament\Form\AddTournamentForm $form
 */

$form = $this->form;
$form->get('title')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter post title here'
]);


$form->prepare();

?>

<h1>Add New Tournament</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('title')); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>
        </div>

        <button type="submit" class="btn btn-warning">Create</button>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

