<?php
/**
 * @var \Tournament\Form\AddTournamentForm $form
 * @var \Tournament\Entity\Tournament[] $tournaments
 */

$form = $this->form;
$form->get('title')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter post title here'
]);


$form->prepare();

?>

<h1>Add New Tournament</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('title')); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>
        </div>

        <button type="submit" class="btn btn-warning">Create</button>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
<hr>
<table class="table table-striped">

    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Created At</th>
    </tr>

    <?php foreach ($tournaments as $tournament): ?>

        <tr>
            <td><?= $this->escapeHtml($tournament->getId()); ?></td>
            <td><?= $this->escapeHtml($tournament->getTitle()); ?></td>
            <td><?= $this->escapeHtml($tournament->getCreatedAt()); ?></td>
            <td>
                <a class="btn btn-success" href="<?= $this->url('application',
                    ['action'=>'start', 'id'=>$tournament->getId()]); ?>">
                    <span class="glyphicon glyphicon-star"></span> Start tournament
                </a>
            </td>
            <td>

                <a class="btn btn-danger" href="<?= $this->url('application',
                    ['action'=>'delete', 'id'=>$tournament->getId()]); ?>">
                    <span class="glyphicon glyphicon-remove"></span> Delete
                </a>
            </td>
        </tr>

    <?php endforeach; ?>

</table>

